parameters:
- name: PoolType
  type: string
  values:
    - 'VM'
    - 'Pool'
  
- name: PoolName
  type: string

- name: LocalVariables
  type: string


stages:
- stage: Build
  displayName: 'CI Build'
  condition: ne(variables['Build.Reason'], 'PullRequest')
  dependsOn: []

  jobs:
  - job: BuildAndPackage
    displayName: 'Build, Test, and Package'
    
    variables:
    - name: revisionDetails
      value: ''
    - template: '${{ parameters.LocalVariables }}@self'
    - template: '../variables/versions.yml'
    
    pool:
      ${{ if eq( parameters.PoolType, 'VM' )}}:
        vmImage: ${{ parameters.PoolName }}
      ${{ if eq( parameters.PoolType, 'Pool' )}}:
        name: ${{ parameters.PoolName }}
    
    steps:
    - checkout: self
      submodules: true

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          $changeFile = Get-Content CHANGELOG.md
          $sb = [System.Text.StringBuilder]::new()
          [void]$sb.AppendLine($changeFile[0])
          for($i = 1; $i -lt $changeFile.Count; $i++){
              if($changeFile[$i].StartsWith("# v")){
                  break
              }
              [void]$sb.AppendLine($changeFile[$i])
          }
          #Write-Output $sb.ToString()
          $releaseNotes = $sb.ToString()
          Write-Output "##vso[task.setvariable variable=revisionDetails]$releaseNotes"
     
    - task: Assembly-Info-NetCore@3
      displayName: 'Set Assembly Info'
      inputs:
        Path: '$(Build.SourcesDirectory)'
        FileNames: '${{ variables.TargetProject }}'
        InsertAttributes: true
        FileEncoding: 'auto'
        WriteBOM: false
        PackageRequireLicenseAcceptance: true
        PackageId: '${{ variables.PackageId }}'
        Authors: '${{ variables.Authors }}'
        Company: '${{ variables.Company }}'
        Product: '${{ variables.Product }}'
        PackageLicenseUrl: '${{ variables.LicenseUrl }}'
        RepositoryUrl: 'https://github.com/${{ variables.RepoName }}'
        PackageIconUrl: '${{ variables.IconUrl }}'
        RepositoryType: '${{ variables.RepoType }}'
        VersionNumber: '$(SemanticVersion).$(Build.BuildId)'
        FileVersionNumber: '$(SemanticVersion).$(Build.BuildId)'
        InformationalVersion: '$(SemanticVersion)'
        PackageVersion: '$(SemanticVersion)'
        PackageReleaseNotes: '$(revisionDetails)'
        LogLevel: 'verbose'
        FailOnWarning: false
        DisableTelemetry: false

    - task: CopyFiles@2
      displayName: 'Copy proj'
      inputs:
        Contents: '${{ variables.TargetProject }}'
        TargetFolder: '$(Build.ArtifactStagingDirectory)\proj'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Changelog'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)\proj'
        ArtifactName: 'proj'
        publishLocation: 'Container'

    - template: '../steps/restore-build-test.yml'
      parameters:  
        HasSqlProj: ${{ variables.HasSqlProj }}
    
    - template: '../steps/package-changelog.yml'

    - ${{ if eq( variables.PostTargetToNuGet, 'yes' )}}:
      - template: '../steps/package-artifacts.yml'
        parameters: 
          PackageToPack: ${{ variables.TargetProject }}
          OutputDir: 'Alpha'
          VersionVariable: 'AlphaVersion'

      - template: '../steps/package-artifacts.yml'
        parameters: 
          PackageToPack: ${{ variables.TargetProject }}
          OutputDir: 'Beta'
          VersionVariable: 'BetaVersion'

      - template: '../steps/package-artifacts.yml'
        parameters: 
          PackageToPack: ${{ variables.TargetProject }}
          OutputDir: 'Release'
          VersionVariable: 'SemanticVersion'

